### ISSUE TITLE
Kreirati klasu plagina

### ISSUE THREAD

**Issue by AlexSensei** [AlexSensei/SOK#4]
Klasa plagina treba da sadrzi sledece:
-Ime plagina 
-Naslov plagina
-Ime java script fajla koji ide uz plagin

Takodje doraditi klasu sa jos odgovarajucih podataka koji budu potrebni za aplikaciju

**Comment by Gambit88** [comment]
Za sada dodato sve sem java script fajla za koji cekam potvrdu strukture.

**Comment by AlexSensei** [comment]
Bice dostavljeno
