### ISSUE TITLE
JS

### ISSUE THREAD

**Issue by AlexSensei** [AlexSensei/SOK#7]
Odraditi odgovarajuci javascript kod za svaki od plaginova

**Comment by Gambit88** [comment]
Koju formu treba da sadrzi javascript kod?

**Comment by AlexSensei** [comment]
Za tvoj da se apenduje forma sa dugmetom za upload i submit dugmetom koja poziva tvoj plagin za konvertovanje HTML koda u stablo koje se zatim zapiseje u data.json ( oko ovoga cemo se jos dogovoriti preko discorda) 

Za Mirin plagin treba dodati opadajucu listu ili neki filter koji pretrazuje gradove za letove i submit dugme koje dalje vrsi potrebne operacije.

I za Nikolu kako njegov plagin radi nisam siguran jos uvek sta zeli da odradi.
